version: "3"
services:
  webserver:
    image: jesugmz/portfolio:dev
    container_name: jesusgomez-webserver
    hostname: jesusgomez-webserver
    volumes:
      - "../src:/var/www"
      - "./webserver/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./webserver/conf/server-block.conf:/etc/nginx/conf.d/jesusgomez.io.conf"
    ports:
      - "80:80"
