#!/bin/bash
# https://docs.docker.com/docker-hub/builds/advanced/
TAG_REGEX="^v([0-9.]+)$" # as it is in Docker Hub

if [[ "$SOURCE_BRANCH" == "master" ]]; then
  echo "---> Building dev image"
  # hooks are relative to the Dockerfile path
  make --directory=../../ build-dev-image
elif [[ "$SOURCE_BRANCH" =~ $TAG_REGEX ]]; then # git tag in format v1.2.3
  echo "---> Building prod image for tag $SOURCE_BRANCH"
  make --directory=../../ build-prod-image
else
  echo "---> The branch name $SOURCE_BRANCH was not recognized, exiting..."
  exit 1
fi
